### ISSUE TITLE
ntfy not working on Raspbian

### ISSUE THREAD

**Issue by Cilusse** [dschep/ntfy#11]
Hello!

I have a problem with ntfy on my Raspberry Pi 2 Model B running the last version of Raspbian. All my packages are up to date.

I installed ntfy with `sudo pip install ntfy` without any error.

If I type just `ntfy`, no problem, the help page is displayed. But when I try to add any argument I have that error : 

> pi@raspberrypi:~ $ ntfy send test
Warning: there was a problem loading ~/.ntfy.json (Expecting property name: line 5 column 3 (char 80))Traceback (most recent call last):
  File "/usr/local/bin/ntfy", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/ntfy/cli.py", line 128, in main
    return send_notification(args.func(args), args, config)
  File "/usr/local/lib/python2.7/dist-packages/ntfy/cli.py", line 74, in send_notification
    **backend_config)
  File "/usr/local/lib/python2.7/dist-packages/ntfy/backends/default.py", line 9, in notify
    module.notify(title=title, message=message, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/ntfy/backends/linux.py", line 7, in notify
    bus = dbus.SessionBus()
  File "/usr/lib/python2.7/dist-packages/dbus/_dbus.py", line 211, in __new__
    mainloop=mainloop)
  File "/usr/lib/python2.7/dist-packages/dbus/_dbus.py", line 100, in __new__
    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 122, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NotSupported: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11

The error is talking about `~/.ntfy.json` but I'm pretty sure that the file is ok because I copied it from the Wiki ^^

Hope you can find a solution :)

**Comment by dschep** [comment]
Hmm, I might have a typo in the wiki, because that is definitely an error in parsing the config. Could you include your config(obviously,  edit out tokens if you're using a backend that uses them)? If you are trying you use the linux desktop notifications (which actually doesn't even require having a config :smile: ), then the second error is relevant too. What desktop environment  or window manager are you running? (eg: gnome, kde, etc)

**Comment by Cilusse** [comment]
Here is my config file : 

> {
  "backend": "pushover",
  "pushover": {
      "user_key": "slkdafjldsajf",
  }
}

(Maybe I'm just too bad and I did it wrong xD )

And I think the desktop manager of Raspbian is LXDE Desktop.

**Comment by dschep** [comment]
Aha. I see the error. Remove the comma at the end of the `"user_key"` line.

**Comment by Cilusse** [comment]
Yep it was that! Thank you and sorry about that uninteresting "issue" :)

**Comment by dschep** [comment]
No problem @Cilusse! I might actually switch the config to YAML (existing JSON would still parse just fine) as it's less strict and this error wouldn't have occured :)
