### ISSUE TITLE
Expose the sound attribute for Pushover Notifications

### ISSUE THREAD

**Issue by tjbenator** [dschep/ntfy#13]
Currently there doesn't seem to be a way to set the sound used on pushover. Is there a possibility of exposing the sound attribute so that it could be used?

https://pushover.net/api#sounds

**Comment by dschep** [comment]
Definitely. I'll consider it for future releases and would gladly accept a pull request.

**Comment by tjbenator** [comment]
I'll have a look this evening. Would love to contribute :)

**Comment by tjbenator** [comment]
My changes were merged. Closing issue.
