### ISSUE TITLE
Uninstall ntfy

### ISSUE THREAD

**Issue by eyalev** [dschep/ntfy#136]
Hi,

I'm trying to uninstall `ntfy`

I've run `sudo pip uninstall ntfy` but currently every time I run a command in my Z shell, I get an error:

````
_ntfy_precmd:9: command not found: ntfy
````

If I run `echo $precmd_functions` I can see `_ntfy_precmd` in this list.

How do I remove it?

Thanks

**Comment by dschep** [comment]
Did you add `eval $(ntfy shell-integration)` to your `.zshrc`? If so, you'll need to remove that too.

**Comment by eyalev** [comment]
> Did you add eval $(ntfy shell-integration) to your .zshrc? If so, you'll need to remove that too.

Yes, I removed that.

**Comment by eyalev** [comment]
I run:
````
precmd_functions=()
````
restarted my zshell, and now it's fine.

Thanks

**Comment by dschep** [comment]
Cool. thanks for letting me know how you fixed it incase anyone else runs into this issue. Sorry I couldn't help much, I don't use zsh personally.

**Comment by eyalev** [comment]
No problem.
Also, this looks like a better solution: http://stackoverflow.com/a/42125494/451710
