### ISSUE TITLE
Feature request: Session-specific backend specification

### ISSUE THREAD

**Issue by pyhedgehog** [dschep/ntfy#138]
I want to be able to pre-select ntfy backend for session using environment variables.
For example:
 1. If I'm accessing computer locally (or at least visually) I want to use `default` backend (be it `linux` or `win32`).
 2. It I'm accessing it via ssh from remote site I'll never see visual notification, so I want to do something like `export NTFY_BACKEND=telegram`.
 3. If I've connected to local computer via ssh (screen/tmux in action) I want to see visual notification, but this session can't connect to my desktop (I mean a windows security object), so I've created service `ntfygw` that connects to daemon running with local session rights that proxies notifications to `default` backend. So I want to do `export NTFY_BACKEND=ntfygw`.

Right now I use `alias ntfy='ntfy -b ntfygw'`, but this is ugly - it doesn't allow to customize another backend for single run.

PS: `ntfygw` is configured like this:
```yaml
ntfygw:
  backend: notifico
  webhook: http://127.0.0.1:3456/
```
And implemented like this:
```python
import logging
import ntfy.config
import flask

app = flask.Flask(__name__)
log = logging.getLogger(app.name)

@app.route('/')
def hook():
    title,message = (flask.request.values.get('payload','').split('\n',1)+[''])[:2]
    ntfy.notify(message, title)
    return 'OK'

if __name__=='__main__':
    logging.basicConfig(level=logging.DEBUG)
    app_port = 3456
    app.debug = True
    app.run(host='127.0.0.1', port=app_port)
```

**Comment by dschep** [comment]
That's a reasonable feature request. I'm thinking in terms of precedence it'd be between the config file and the comandline flag.

Clever script too 👍
