### ISSUE TITLE
Pushover clone URL

### ISSUE THREAD

**Issue by jcs** [dschep/ntfy#146]
(Pushover developer here)

I've raised ntfy's monthly message limit for its hard-coded API token to 15,000 messages per month, though it would be best if all users were directed to create their own API token so this kind of issue doesn't happen again.

You can direct users to https://pushover.net/apps/clone/ntfy which is easier than the /apps/build URL.  Users can just check the box and click Create, and it will have a proper icon and everything already filled out.

**Comment by dschep** [comment]
Awesome! Thanks for the limit bump. I didn't know there was a clone app feature, that's perfect :smiley:
