### ISSUE TITLE
How to install the backends?

### ISSUE THREAD

**Issue by scalp42** [dschep/ntfy#155]
I can't figure how to enable the other backends:

```
$> ntfy -b emoji send :tada:
```

The documentation is not clear either on what to run from command-line.

Much appreciated!

**Comment by scalp42** [comment]
Having a long day:

```
$> pip3 install ntfy\[pid,emoji,slack,hipchat\]
```

**Comment by dschep** [comment]
Hah, no worries. Glad you figured it out! :smile:

**Comment by scalp42** [comment]
Opened https://github.com/dschep/ntfy/pull/156 @dschep 🎱
