### ISSUE TITLE
syslog message over telegram?

### ISSUE THREAD

**Issue by Nastras** [dschep/ntfy#172]
Hello, I would like to send with ntfy and telegram me a syslog file is that possible?

I have seen that there is a systemlog extension, but I do not quite understand how I would use this?

Thanks for your help.

**Comment by dschep** [comment]
They syslog backend if for writing to syslog, not reading. If you read syslogs in a script you can use ntfy to send it through telegram, but as the message body, not an attached file.

**Comment by Nastras** [comment]
Thank you for the answer. I have found a solution over the Telegram API to send a Message with attached file.

I think for ntfy it would be a great extension to send files.
