### ISSUE TITLE
Include python-dbus as a dependency

### ISSUE THREAD

**Issue by fayoh** [dschep/ntfy#179]
When following the quickstart guide ntfy defaulted to using dbus and complained about missing the library.

If this is the default behaviour for all platforms I would like to see python-dbus listed as a mandatory dependency instead of briefly mentioning it later in the readme

**Comment by dschep** [comment]
The reason it's this way is that this way, `pip install ntfy` works on linux systems reliably, and if the user wants desktop notifications they need to run(on a deb system for example) `apt install python-dbus`. 

On the other hand, if `dbus-python`(the PyPi name of the module) was a python dependency of ntfy, `pip install ntfy` wouldn't work unless all the compile time dependencies of python-dbus are present (eg `apt install libdbus-glib-1-dev libdbus-1-dev python-dev` on a deb system).

The real solution, IMO, is to package ntfy as a deb/rpm/etc that has proper dependencies on precompiled python-dbus system packages.

I've made a few tweaks to the readme in 280f30c just now.

Furthermore, when I first wrote ntfy, python-dbus was pre-installed on Ubuntu, which made things much simpler. Looking at https://pypi.org/project/dbus-python/#description I realize that there probably still are some form of DBUS bindings preinstalled (either GDBus or QtDBus for Gnome & KDE based systems respectively) so I should look into using those when they're available too.

**Comment by dschep** [comment]
Notes for using `glib` which is available on any Gnome based system: https://www.devdungeon.com/content/desktop-notifications-linux-python

**Comment by fayoh** [comment]
I see your reasoning, I usually have quite a few dev packages installed so I never thought of it that not everyone does :) Plus on my old company mandated debian I rarely use system python packages anyway since they are often too out of date.

And yes, agreed os-level packaging is the real solution. With all the work that implies.

Thanks for the readme update.

Cheers
