### ISSUE TITLE
with only pushover defined in backend config, still get DefaultNotifierError

### ISSUE THREAD

**Issue by thoraxe** [dschep/ntfy#185]
```yaml
backends: 
  - pushover
pushover: 
  user_key: xxx
```

```bash
[root@ip-172-31-27-123 ~]# ntfy send test
ERROR: Failed to send notification using default
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ntfy/__init__.py", line 58, in notify
    **backend_config)
  File "/usr/lib/python2.7/site-packages/ntfy/backends/default.py", line 22, in notify
    raise DefaultNotifierError(e, module)
DefaultNotifierError
```

Same failure happens whether or not I have `~/.ntfy.yaml` or `~/.config/ntfy/ntfy.yaml`

`ntfy 2.6.0` on `Linux ip-172-31-27-123.ec2.internal 3.10.0-957.el7.x86_64 #1 SMP Thu Oct 4 20:48:51 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

specifying the backend explicitly via `ntfy -b pushover ....` works.

**Comment by dschep** [comment]
The config file should have the name `ntfy.yml` not `ntfy.yaml`
