### ISSUE TITLE
How does termux:API work?

### ISSUE THREAD

**Issue by shanness** [dschep/ntfy#190]
Hey,

Great project!  Just wondering how the termux:API is designed to be used? Does it require ntfy on the phone?

**Comment by dschep** [comment]
Yup, it's intended for use entirely on your phone. Think of it as the Android equivalent of the `windows`/`darwin`/`linux` backend for desktop computers.

To use it (let me know if you have any issues, it was built mostly as a curiosity and I never actually use it) follow these steps:
1. install Termux https://play.google.com/store/apps/details?id=com.termux
2. install Termux:API https://play.google.com/store/apps/details?id=com.termux.api
3. open Termux
4. install termux api client: `apt install termux-api`
5. install ntfy: `pip install ntfy`
6. Test it!: `ntfy -b termux send test`

**Comment by Dan1jel** [comment]
Tried this agan after using a different method, but now I get this error instead (termux ans termux api is installed via F-droid i stead due to play version is outdated. 

```
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/ntfy", line 5, in <module>
    from ntfy.cli import main
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/ntfy/__init__.py", line 6, in <module>
    from inspect import getargspec
ImportError: cannot import name 'getargspec' from 'inspect' (/data/data/com.termux/files/usr/lib/python3.11/inspect.py)
```

**Comment by dschep** [comment]
Hey @Dan1jel, it looks like `inspect.getargspec` was removed in python 3.11. I created #262 to track this bug.
