### ISSUE TITLE
Add support for fish shell

### ISSUE THREAD

**Issue by andrewgazelka** [dschep/ntfy#212]

**Comment by andersmmg** [comment]
You can just add something like this to your prompt file:

```
if test $CMD_DURATION
    if test $CMD_DURATION -gt (math "1000 * 10")
        set secs (math "$CMD_DURATION / 1000")
        ntfy -t "$history[1]" send "Returned $status, took $secs seconds"
    end
end
```

**Comment by andrewgazelka** [comment]
Thanks!

**Comment by zeorin** [comment]
`ntfy` can be used as a custom command with https://github.com/franciscolourenco/done. `done` can handle figuring out whether a command should be ignored, whether the threshold time has been reached, whether the terminal is in the foreground or not, and `ntfy` can then handle the notification.
