### ISSUE TITLE
shell integration

### ISSUE THREAD

**Issue by dschep** [dschep/ntfy#22]
See https://github.com/jml/undistract-me for an example

Main concern is long running interactive jobs. Ie, I don't want a notification for `vim`.

**Comment by jungle-boogie** [comment]
Hello,

I believe I'm now following 1.1.1 branch:

```
ntfy --version
1.1.1
```

I put `eval "$(ntfy shell-integration)"` in my .zsh and then `source .zsh`:

```
% source .zshrc 
usage: ntfy [-h] [-c CONFIG] [-b BACKEND] [-o key value]
            [-l {CRITICAL,ERROR,WARNING,INFO,DEBUG}] [-v] [-q] [--version]
            [-t TITLE]
            {send,done} ...
ntfy: error: invalid choice: 'shell-integration' (choose from 'send', 'done')
```

Is this still a WIP?

**Comment by dschep** [comment]
Yeah it's not merged yet. See #24. If you want to try it out, install it from github:
```
sudo pip3 install -U git+https://github.com/dschep/ntfy@auto-ntfy-done#egg=ntfy
```

Then you should get:
```
$ ntfy --version
1.1.1.post1
$ ntfy shell-integration
export AUTO_NTFY_DONE_EMOJI=true
source /usr/local/lib/python3.4/dist-packages/ntfy/shell_integration/bash-preexec.sh
source /usr/local/lib/python3.4/dist-packages/ntfy/shell_integration/auto-ntfy-done.sh
# To use ntfy's shell integration, run this and and it to your shell's rc file:
# eval "$(ntfy shell-integration)"
```

**Comment by jungle-boogie** [comment]
Okay, I think I set this up correctly.

version:
```
% ntfy --version
1.1.1.post1
```

```
% ntfy shell-integration
source /usr/local/lib/python3.4/site-packages/ntfy/shell_integration/auto-ntfy-done.sh
# To use ntfy's shell integration, run this and and it to your shell's rc file:
# eval "$(ntfy shell-integration)"
```

Here it is in my .zshrc:
```
% ack 'ntfy shell-integration' .zshrc 
eval "$(ntfy shell-integration)"
```

Here's the error:
```
% sleep 31                                     
ntfy_precmd:13: = not found
```

**Comment by dschep** [comment]
Thanks for trying it! I'm mostly a bash user so there may be a regression since the last time I tested zsh. I'll test it again and let you know what I find.

**Comment by jungle-boogie** [comment]
> I'll test it again and let you know what I find.

Super, let me know if I can help test it again.

**Comment by dschep** [comment]
I just pushed a change that should fix zsh support. Run the install I described above the same way again and give it a shot.

**Comment by jungle-boogie** [comment]
Thanks, @dschep. You fixed it!

I'll try it out and see if there's any other issues.
