### ISSUE TITLE
 emojize() got an unexpected keyword argument 'use_aliases'

### ISSUE THREAD

**Issue by Xenon4416** [dschep/ntfy#251]
just executing `ntfy send "test"` gives following error
```
Traceback (most recent call last):
  File "/usr/local/bin/ntfy", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/ntfy/cli.py", line 361, in main
    message = emojize(message, use_aliases=True)
TypeError: emojize() got an unexpected keyword argument 'use_aliases'
```

**Comment by cvzi** [comment]
This happens because of version 2.0.0 of the emoji module. As a workaround you can install an older version e.g. [1.6.3](https://github.com/carpedm20/emoji/releases/tag/v1.6.3)
```sh
pip install --upgrade emoji==1.6.3
```

**Comment by Xenon4416** [comment]
thanks, it worked for me..

**Comment by tushev** [comment]
@dschep can we please remove [use_aliases](https://github.com/dschep/ntfy/blob/master/ntfy/cli.py#L361C40-L361C51) since it's deprecated?

https://github.com/carpedm20/emoji/pull/205

**Comment by vermavinay982** [comment]
The use_aliases argument is deprecated, and replaced with mentioning language as 'alias' - using emoji version 2.9.0 

```python
emoji.emojize("python is cold :panda::cold_face:", language='alias')

# Output: 'python is cold 🐼🥶'
```


https://stackoverflow.com/a/77673372/10042411
