### ISSUE TITLE
Can not use shell variable as message

### ISSUE THREAD

**Issue by Fuad-HH** [dschep/ntfy#254]
I am using ntfy with in shell script. A python script prints a string which is assigned to a variable and I can `echo` the variable. But if I use this as `ntfy -t "Title" send $var` it returns an error. Is there a way to use a variable as ntfy's input?

**Comment by dschep** [comment]
I'm guessing `$var` has spaces. It should work just fine. this is a shell concern, not a `ntfy` concern. Shells evaluate variables before calling programs. You probably just need to to do this:
```shell
ntfy -t "Title" send "$var"
```
