### ISSUE TITLE
ntfy done -t

### ISSUE THREAD

**Issue by jungle-boogie** [dschep/ntfy#26]
Hello,

Can the -t option also be added for the `ntfy done` setting?
https://github.com/dschep/ntfy/blob/master/ntfy/cli.py#L84-L88

**Comment by dschep** [comment]
Yup. This works as expected:
```
$ ntfy -t 'custom title here' done sleep 1
```

*NOTE:* the `-t` option is on the main command not the `done` or `send` subcommand so it has to be before them.
