### ISSUE TITLE
Investigate getting rid of libnotify-bin linux dependency

### ISSUE THREAD

**Issue by dschep** [dschep/ntfy#3]
Should maybe just use pygtk and so forth, downside of this is that they can't be pip installed, similar to Mac OS X notifications.

**Comment by arusahni** [comment]
This may be reasonable if you're targeting users with GTK.  As a KDE user, `python-gtk2-dev` pulls down 50 packages totaling 70MB.  Much more of an imposition than the 1, 70KB install of `libnotify-bin`.  If PyGTK is installed by default on many GTK systems, maybe just test for the `notify-send` binary in the path (or catch the PyGTK `ImportError`) and fall back to attempting the other?

**Comment by dschep** [comment]
Is there an similar KDE library that could be imported?

**Comment by arusahni** [comment]
Yes. To keep it in Python-land (preferred):

```python
import dbus

knotify = dbus.SessionBus().get_object("org.kde.knotify", "/Notify")
event_id = knotify.event("warning", "kde", [], "TITLE", "MESSAGE", [], [], 0, 0, dbus_interface="org.kde.KNotify")
```

The `event()` call [has this signature](http://api.kde.org/4.x-api/kde-runtime-apidocs/knotify/html/classKNotify.html#aa337013a8c77dde32e4228a9467a3765).  The advantage of using this is you get a handle for the created dialog, letting you do things like close the notification (i.e. `knotify.closeNotification(event_id)`).

If you'd rather shell out (ew), `kdialog --title "TITLE" --passivepopup "MESSAGE" 5`.
