### ISSUE TITLE
ntfy for pid

### ISSUE THREAD

**Issue by jungle-boogie** [dschep/ntfy#36]
Hello,

I have `1.2.0.post13` how do I get the pid functionality?

```
Send push notification when command finishes

positional arguments:
  {send,done,shell-integration}
    send                send a notification
    done                run a command and send a notification when done
    shell-integration   automatically get notifications when long running
                        commands finish     
```

**Comment by dschep** [comment]
Do you have `psutil` installed? I haven't fully updated the docs (nor cut a release) with how to install the extras. Just run `pip install psutil`. I think there might be a bug in the pid functionality, but I'm not sure. Then:
```
$ ntfy done -h
usage: ntfy done [-h] [-L N] [-p PID] ...

positional arguments:
  command               command to run

optional arguments:
  -h, --help            show this help message and exit
  -L N, --longer-than N
                        Only notify if the command runs longer than N seconds
  -p PID, --pid PID     Watch a PID instead of running a new command
```

**Comment by jungle-boogie** [comment]
> Do you have psutil installed?

I installed it and I still don't see PID as an option with ntfy. I'll wait until you make a release.

**Comment by dschep** [comment]
Weird. I'll probably cut a release soon, I've been testing the `--pid` functionality at work today and it seems to work. I personally install ntfy with `pip3`, so if you do that too, you need to make sure you install psutil that way too.

**Comment by jungle-boogie** [comment]
Okay, I'll try it then and on a couple different machines to see if I see different behavior.

Along the same lines as watching a pid, have you considered notifying when a command starts up?
