### ISSUE TITLE
Get ntfy.yaml from /etc

### ISSUE THREAD

**Issue by mrdrogdrog** [dschep/ntfy#41]
It would be nice if ntfy could read the config from /etc/ntfy/ntfy.yaml if no ~/config/ntfy/ntfy.yaml exists.

**Comment by jungle-boogie** [comment]
BSD systems would prefix /etc with `/usr/local/`.

**Comment by mrdrogdrog** [comment]
I'm also ok with that.

**Comment by dschep** [comment]
@jungle-boogie, unrelated to this, but related to BSD: should the [`default` backend](https://github.com/dschep/ntfy/blob/master/ntfy/backends/default.py) check for `os.environ.get('DISPLAY') is not None` instead of `sys.platform.startswith('linux')` to better support BSDs?

**Comment by jungle-boogie** [comment]
@dschep, hmmm, I don't know enough to comment. PCBSD is a freebsd desktop version but my laptop is too new for it.

I recommend keeping it as is and see if anyone running PCBSD and/or openbsd complain notifications are not being displayed.
