### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'pid'

### ISSUE THREAD

**Issue by thereisnosec** [dschep/ntfy#42]
By calling `ntfy done sleep 2` I'm getting:
```
Traceback (most recent call last):
  File "/usr/local/bin/ntfy", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/ntfy/cli.py", line 247, in main
    message = args.func(args)
  File "/usr/local/lib/python2.7/dist-packages/ntfy/cli.py", line 26, in run_cmd
    if args.pid:
AttributeError: 'Namespace' object has no attribute 'pid'
```
It does not matter what I append to `done`. I'm getting the same Traceback.
Anyway what is the correct syntax for calling `ntfy done` with a `pid`?
I'm using ntfy 1.3.0 including ntfy[emoji] and ntfy[pid].

**Comment by dschep** [comment]
Hmm, the fact you install ntfy[pid] makes this surprising. There probably _is_ a bug when psutil isn't installed, but I'm not sure why you see it.

**Comment by dschep** [comment]
I've just pushed `v1.3.1` (it might take a few minutes to go through Travis CI & get uploaded to PyPi). It should address this traceback.

**Comment by thereisnosec** [comment]
thx, just upgraded to 1.3.1 and `ntfy done sleep 2` is working as expected.
But how do i use a pid of a running process instead of running a new process?
I would expect `ntfy done 6279` or `ntfy done pid=6279`, but neither work.

**Comment by dschep** [comment]
It's `ntfy done -p 6379` or `ntfy done --pid 6379`. You need to have `psutil` installed, installing `ntfy[pid]` should've taken care of that. If the commands I gave don't work, just run `sudo pip install psutil` and that should fix it :smiley:
