### ISSUE TITLE
Single file executable

### ISSUE THREAD

**Issue by dschep** [dschep/ntfy#43]
Options:
* [PyInstaller](http://www.pyinstaller.org/) (crossplatform)
* py2exe (windows)
* cxfreeze (linux)
* py2app (macoss)

A potential pitfall: [`virtualenv` issue](https://github.com/dschep/ntfy#install). Possible solution (tested on Linux): create virtualenv but then use system python and add that virtualenv's site-packages to `PYTHONPATH`. (or.. just `pip install --target`)

**Comment by kamilchm** [comment]
or https://github.com/pantsbuild/pex

**Comment by dschep** [comment]
Thanks @kamilchm, I've tried pex. I haven't found a way to get dbus notifications to work with it :cry:
