### ISSUE TITLE
WARNING: Failed to send notification using linux

### ISSUE THREAD

**Issue by dixudx** [dschep/ntfy#56]
After installing the dependencies, I tried ntfy.

```
root@3b84f399b67d:~# ntfy -b linux -v send 'test'
WARNING: Failed to send notification using linux
root@3b84f399b67d:~# ntfy send test
WARNING: Failed to send notification using linux
root@3b84f399b67d:~# ntfy done sleep 2
WARNING: Failed to send notification using linux
```

Without any other exceptions showing, I can not find out the root cause.

**Comment by jungle-boogie** [comment]
What's your config file look like?

**Comment by dixudx** [comment]
Just a small yaml file with only `linux` backend.

```yaml
backends:
    - linux
```

**Comment by dschep** [comment]
I presume you have v1.3.2 installed from pip? That message is because dbus is raising an exception. I probably shouldn't be handling those exceptions any differently [here](https://github.com/dschep/ntfy/blob/f1679ea623c1f16ef6ba878350708c19ebad1424/ntfy/__init__.py#L44-L46) from the other exceptions.

The master branch here is way ahead of v1.3.2 (adding some features for a 2.0 release), but I can definitely make a release for you to test that should help with debugging that error :smiley: (or you can just delete those lines from your `ntfy/__init__.py` in site-packages.

**Comment by dixudx** [comment]
Yeah, you got it. The version I installed is precisely v1.3.2.

After manually removing the lines according to your patchset, I fixed the error in my box.

Thanks for your investigating.

**Comment by dschep** [comment]
@dixudx, by that do you mean it gave you a trace back that allowed you to find what was wrong? If so, mind sharing what the problem was?

**Comment by dixudx** [comment]
@dschep It was quite funny. Actually I've made a wrong decision from the beginning.

I intended to install `ntfy` in a container. During the installation, several packages (Ubuntu/Debian OS) needed to be installed.

```bash
$ apt-get install -y python-pip pkg-config python-dev libdbus-1-dev libdbus-glib-1-dev
$ pip install dbus-python ntfy
```

```bash
$ ntfy send "test"
WARNING: Failed to send notification using linux
```

After applying your patchset (removing the lines on exception handling),

```bash
$ ntfy send "test"
ERROR: Failed to send notification using default
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ntfy/__init__.py", line 41, in notify
    module.notify(message=message, title=title, **backend_config)
  File "/usr/local/lib/python2.7/dist-packages/ntfy/backends/default.py", line 13, in notify
    module.notify(title=title, message=message, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/ntfy/backends/linux.py", line 19, in notify
    bus = dbus.SessionBus()
  File "/usr/local/lib/python2.7/dist-packages/dbus/_dbus.py", line 211, in __new__
    mainloop=mainloop)
  File "/usr/local/lib/python2.7/dist-packages/dbus/_dbus.py", line 100, in __new__
    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
  File "/usr/local/lib/python2.7/dist-packages/dbus/bus.py", line 122, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
DBusException: org.freedesktop.DBus.Error.NotSupported: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11
$ export DISPLAY=:0
$ ntfy send "test"
process 11181: D-Bus library appears to be incorrectly set up; failed to read machine uuid: Failed to open "/etc/machine-id": No such file or directory
See the manual page for dbus-uuidgen to correct this issue.
ERROR: Failed to send notification using default
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ntfy/__init__.py", line 41, in notify
    module.notify(message=message, title=title, **backend_config)
  File "/usr/local/lib/python2.7/dist-packages/ntfy/backends/default.py", line 13, in notify
    module.notify(title=title, message=message, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/ntfy/backends/linux.py", line 19, in notify
    bus = dbus.SessionBus()
  File "/usr/local/lib/python2.7/dist-packages/dbus/_dbus.py", line 211, in __new__
    mainloop=mainloop)
  File "/usr/local/lib/python2.7/dist-packages/dbus/_dbus.py", line 100, in __new__
    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
  File "/usr/local/lib/python2.7/dist-packages/dbus/bus.py", line 122, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
DBusException: org.freedesktop.DBus.Error.Spawn.ExecFailed: //bin/dbus-launch terminated abnormally without any error message
```

Until now, I realised that this ubuntu box was running in a container without any GUI, not a desktop version.

Then I turned to my Ubuntu desktop and installed `ntfy`. Everything works perfect.

Thanks so much for your effort and time to solve my stupid problem.

**Comment by dschep** [comment]
Hah, yup that would definitely cause problems. `ntfy`'s cloud notification support exists for this very reason. I also have to work in VMs or containers often. I use [Pullover](https://github.com/cgrossde/Pullover) on my host OS and have a `.ntfy.yml` in the VM/container setup to use Pushover with my desktop as the device, so it doesn't go to my phone and other computers too.
