### ISSUE TITLE
Allow using multiple backends at once

### ISSUE THREAD

**Issue by dschep** [dschep/ntfy#6]
It could be useful to use both desktop and cloud notifications at the same time.

Config example:
```
{
    "backend": ["default", "pushbullet"],
    "pushbullet": {"access_token": "<redacted>"}
}
```

CLI Example:
```
ntfy -b default,pushbullet send foobar
```

Suggested by @danryder as well.

**Comment by PaulDebus** [comment]
Hey,
thanks for the great tool! Is this issue closed because it is working like this? 

Cheers

**Comment by dschep** [comment]
Yes, for 2 years now 😉 

Per the [README](https://github.com/dschep/ntfy#backends) the `backends` config key in `ntfy.yml` is a list. To use it on the command line, this PR's example is wrong, you want:
```
ntfy -b default -b pushover send foobar
```

**Comment by PaulDebus** [comment]
Ah, I see, that's awesome. Thanks!
