### ISSUE TITLE
ntfy done: error: argument --formatter: expected 3 arguments

### ISSUE THREAD

**Issue by jungle-boogie** [dschep/ntfy#61]
```
% ls -l
...
ntfy done: error: argument --formatter: expected 3 arguments
```

This is with the single binary and with zsh AUTO_NTFY_DONE setup. Will I need to continue to use pip for auto shell integration?

**Comment by dschep** [comment]
This is most likely because you have 2 versions of ntfy installed now. OR you upgraded and haven't restarted your shell maybe?

**Comment by jungle-boogie** [comment]
Well it looks like I had only one ntfy installed so I deleted the binary and the directory at
/usr/home/jungle/.local/share/ntfy
then `suod python3 setup.py install` in the ntfy directory. 

in zsh:
```
eval "$(ntfy shell-integration)"
AUTO_NTFY_DONE_TIMEOUT=40
AUTO_NTFY_DONE_IGNORE='atop emacs gstat info less lua53 jupyter mail man meld most mutt nano screen ssh sqlite3 tail tmux top vi vim'
```

Logout and login of the shell and `ls`:
`ntfy done: error: argument --formatter: expected 3 arguments`


I'm running zsh shell on freebsd with zsh installed at: /usr/local/bin/zsh

Do you have this same problem with a similar environment?

**Comment by dschep** [comment]
Can you give me the output of the following commands?
```shell
$ ntfy --version
$ ntfy done -h
$ ntfy shell-integration
```
And the contents of the `auto-ntfy-done.sh` file in the output of `ntfy shell-integration`.

**Comment by jungle-boogie** [comment]
```
% ntfy --version
2.0.1               
```

```
% ntfy done -h
usage: ntfy done [-h] [-L N] [-b] [--formatter command retcode duration]
                 [-p PID]
                 ...

positional arguments:
  command               command to run

optional arguments:
  -h, --help            show this help message and exit
  -L N, --longer-than N
                        Only notify if the command runs longer than N seconds
  -b, --background-only
                        Only notify if shell isn't in the foreground
  --formatter command retcode duration
                        Format and send cmd, retcode & duration instead of
                        running command. Used internally by shell-integration
  -p PID, --pid PID     Watch a PID instead of running a new command
```

```
% ntfy shell-integration
export AUTO_NTFY_DONE_LONGER_THAN=-L10
export AUTO_NTFY_DONE_UNFOCUSED_ONLY=-b
source /home/sean/.local/share/ntfy/auto-ntfy-done.sh
# To use ntfy's shell integration, run this and and it to your shell's rc file:
# eval "$(ntfy shell-integration)"
```

Here's the contents of auto-ntfy-done.sh:
https://gist.github.com/jungle-boogie/db03b0c0c168dd2ab67e0b83f14a48d9

**Comment by dschep** [comment]
Crap. I think this only fixes bash @jungle-boogie

**Comment by jungle-boogie** [comment]
Right, looks like same behavior on latest release.

By the way, doesn't look like you changed the version number and still shows 2.0.1.

**Comment by dschep** [comment]
Yeah, noticed that too. Forgot I wasn't using tags for the version number anymore. Fixing 2.0.2, 2.0.3 should fix zsh too when I get to that (probably next week, not gonna be on a computer for ~3 days :smiley: )

**Comment by jungle-boogie** [comment]
> not gonna be on a computer for ~3 days 

Enjoy that time away!

**Comment by rcaloras** [comment]
@dschep Looking at f30f314. Rather than accessing the underlying variables internal to bash-preexec, you should be able access the last ret value simply using `$?` at the beginning of your precmd function. That is of course agnostic to shell type :) and might fix for zsh as well.

**Comment by dschep** [comment]
Fixed by #63.

**Comment by jungle-boogie** [comment]
verified! Thanks for the contributions @rcaloras !

**Comment by rcaloras** [comment]
@jungle-boogie you're welcome! Love contributing and thrilled to see people using my open source projects 👍
