### ISSUE TITLE
Comparison between string and int when giving optional priority argument on command line

### ISSUE THREAD

**Issue by teamalpha5441** [dschep/ntfy#62]
Executing ntfy with Pushover backend this way:
$ ntfy -o priority 2 send "f*ck"

yields to this error:
ERROR: Failed to send notification using pushover
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/ntfy/__init__.py", line 30, in notify
    module.notify(message=message, title=title, **backend_config)
  File "/usr/lib/python3.5/site-packages/ntfy/backends/pushover.py", line 63, in notify
    if priority <= 2 and priority >= -2:
TypeError: unorderable types: str() <= int()

https://github.com/dschep/ntfy/blob/master/ntfy/backends/pushover.py#L63

**Comment by dschep** [comment]
Good catch, this was a contributed feature I don't use so I never ran into this bug.

**Comment by teamalpha5441** [comment]
Thank you for your fast response and project!
