### ISSUE TITLE
ntfy shell integration ignoring timeout

### ISSUE THREAD

**Issue by jungle-boogie** [dschep/ntfy#64]
Hi,

Version of ntfy: 2.0.3
Platform: i386 freebsd
python version: 3.4.4

shell integration in my .zshrc:
```
eval "$(ntfy shell-integration)"
AUTO_NTFY_DONE_TIMEOUT=60
AUTO_NTFY_DONE_IGNORE='atop emacs gstat info less lua53 jupyter mail man meld most mutt nano screen ssh sqlite3 tail tmux top vi vim' 
```

On the client.pushover.com site:

```
jungle@host.in.example.net:/usr~
"sleep 50" succeeded in 0:50 minutes
```

Does this happen with your bash integration?

**Comment by dschep** [comment]
That's what happens when I suck at documenting changes :disappointed:

The feature is now a handled in a unified fashion in the python codebase for done & shell-integration. Use this instead:
```
eval "$(ntfy shell-integration -L60)"
AUTO_NTFY_DONE_IGNORE='atop emacs gstat info less lua53 jupyter mail man meld most mutt nano screen ssh sqlite3 tail tmux top vi vim'
```
