### ISSUE TITLE
Telegram support

### ISSUE THREAD

**Issue by rahiel** [dschep/ntfy#66]
ntfy is nifty. Are you interested in adding support for [Telegram](https://telegram.org/)? I made a [package](https://github.com/rahiel/telegram-send) that could be used. It has a `configure` function to guide users in setting it up and a `send` function to send stuff.
```python
conf = "~/.config/ntfy/telegram-send.conf"
telegram_send.configure(conf)
telegram_send.send(messages=["hello"], conf=conf)
```
That call to `configure` saves the credentials (api token, and which user to send messages to) in the `conf` file and the call to `send` uses it to send a message.

I'd like to help if you're interested.

**Comment by dschep** [comment]
I'm not personally interested, as I'm not a user, but I'm open to PRs :smile: 

If it requires a dependency, that should be an extra (see xmpp for [example](https://github.com/dschep/ntfy/blob/08f2f1ec34cc67da655c9b40e62fe9a90feaff09/setup.py#L10-L11))
