### ISSUE TITLE
Better error when missing config keys

### ISSUE THREAD

**Issue by dschep** [dschep/ntfy#69]
Currently get messages like this, which aren't useful to users:
```
ERROR: Failed to send notification using pushover
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ntfy/__init__.py", line 30, in notify
    module.notify(message=message, title=title, **backend_config)
TypeError: notify() takes at least 3 arguments (2 given)
```

If possible, introspect the function signature to find what the arguments accepted are.

**Comment by hulinghuan** [comment]
Hi 

The problem you posted can be fixed if you change the syntax of command as shown in the following:
`ntfy -b pushover -o user_key [your_user_key] send 'aha'`

I think this might help other users if they are currently trying to use ntfy to push notification through pushover.

**Comment by sambrightman** [comment]
I think this is currently hiding problems with the integration tests. Run alone, they pass. However,  `args.options` state is incorrectly shared between tests, breaking them when all tests are run. Since they are not verifying the exit code, this change is hiding the problem. See #114.
