### ISSUE TITLE
Context Manager based notifier

### ISSUE THREAD

**Issue by Socialery** [dschep/ntfy#78]
Just a random silly idea: using a context manager to help with notifying about tasks

Would intergrate well and easily with personal python scripts n' stuff, or any codebases which would benefit from being able to easily add in notifications (buildbots perhaps?)

(note: the following code isn't exactly clean or complete, if you want this to be made into a pull request or whatever, I can)

``` python
class TaskNotifier:
    def __init__(self, task_name, on_enter=True, on_exit=True, on_error=True,
                 config=None, **kwargs):
        self.task_name = task_name
        self.on_enter = on_enter
        self.on_exit = on_exit
        self.on_error = on_error
        self.config = config
        self.kwargs = kwargs

    def __enter__(self):
        # start_time = now()
        if self.on_enter:
            # questionmark notification icon?
            ntfy.notify("Task: {}".format(self.task_name),
                        "task has started!")

    def __exit__(self, exc_type, exc_value, traceback):
        # task_time = start_time - now()
        # task_time = enprettyfy(task_time)
        if exc_type and self.on_error:
            # X notification icon?
            ntfy.notify("Task: {}".format(self.task_name),
                        "task has errored out after {}!".format(task_time))
        elif self.on_exit:
            # Tick notification icon?
            ntfy.notify("Task: {}".format(self.task_name),
                        "task has finished in {}!".format(task_time))
        # if self.suppress_error: return true ?
```

It would also simplify the whole run-a-process command already within the library (not that it isn't already)

``` python
def for_a_process_thing(commandline):
    with TaskNotifier(commandline):
        subprocess.check_call(commandline)
```

However this is just a silly idea, a tad bit complicated for what it does, and might not be worth the maintenance cost! but if you like the idea, I'd be happy to implement it for you

**Comment by lcd1232** [comment]
I think it's very good idea.

**Comment by PaulDebus** [comment]
I think a decorator would be even more suitable for this job:

```python
@ntfy
def something():
   do_something()
```
what do you think @Socialery

**Comment by dschep** [comment]
Both are perfectly fine ideas, but I'm not hard pressed to use or implement them myself, but I'll accept a good PR for either or both.
