### ISSUE TITLE
Pushover's access_token not recognized

### ISSUE THREAD

**Issue by nmaggioni** [dschep/ntfy#82]
If setting the `access_token` option for Pushover (as mentioned [in the Readme](https://github.com/dschep/ntfy#pushover---pushover) and [in the code's documentation](https://github.com/dschep/ntfy/blob/f7c5b53fd50167f4c833c94c974618c0e13ac93e/ntfy/backends/pushover.py#L31)), the following error is printed in the console:

```text
ERROR: Got unknown arguments: {'access_token'}
```

The same happens if specifying options through the CLI:

```bash
$ ntfy -b pushover -o user_key MYUSERKEY -o access_token MYACCESSTOKEN send 'Pushover test!'
ERROR: Got unknown arguments: {'access_token'}
```

**Comment by dschep** [comment]
Seems like a mistake, I'll have to update the docs. It's `api_token` actually: https://github.com/dschep/ntfy/blob/f7c5b53fd50167f4c833c94c974618c0e13ac93e/ntfy/backends/pushover.py#L10
