### ISSUE TITLE
Pushbullet not working

### ISSUE THREAD

**Issue by nsvir** [dschep/ntfy#83]
I have an issue with the pushbullet backend:
```
> ntfy -b pushbullet send "hey"
Traceback (most recent call last):
  File "/usr/bin/ntfy", line 11, in <module>
    load_entry_point('ntfy==2.1.1', 'console_scripts', 'ntfy')()
  File "/usr/lib/python3.5/site-packages/ntfy/cli.py", line 304, in main
    **dict(args.option.get(None, [])))
  File "/usr/lib/python3.5/site-packages/ntfy/__init__.py", line 34, in notify
    backend_config.update(kwargs)
AttributeError: 'NoneType' object has no attribute 'update'
```

```
cat ~/.config/ntfy/ntfy.yml 
backends:
- linux
- pushbullet

pushbullet:
access_key: <my_key>
```

**Comment by nsvir** [comment]
pushbullet needs 'acces_token' and not 'access_key' like suggested in the backend example: https://github.com/dschep/ntfy#backends.
The pushbullet doc is right btw: https://github.com/dschep/ntfy#pushbullet---pushbullet

**Comment by dschep** [comment]
Good catch. I'll update the example in the Readme

**Comment by bendem** [comment]
Came here to say that, glad you already know about it. While you are at it, might be worth adding 
```sh
curl --header 'Access-Token: <youknow>' \
    https://api.pushbullet.com/v2/devices \
    | jq '.devices[] | select(.active == true)'
```
to the pushbullet section to list device identifiers you can pass to `device_iden`.
