### ISSUE TITLE
did it support mac?

### ISSUE THREAD

**Issue by csrgxtu** [dschep/ntfy#87]
did it support mac?

**Comment by minhoryang** [comment]
https://github.com/dschep/ntfy#mac-os-x-notification-center---darwin

**Comment by dcoeurjo** [comment]
I don't know if my issue is related to you.. However, on a ```ntfy```fresh install using pip, when I ```ntfy -b darwin send "helloworld"```, I got this:

```
ERROR: Failed to send notification using darwin
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/ntfy/__init__.py", line 48, in notify
    **backend_config)
  File "/usr/local/lib/python2.7/site-packages/ntfy/backends/darwin.py", line 6, in notify
    import Foundation
ImportError: No module named Foundation
```

any idea?

**Comment by dschep** [comment]
Hmm. What version of MacOS? It doesn't look like you installed it in a virtualenv.. so I'm not really sure. I'm pretty limited in my debugging capabilities tho since I don't use a Mac.

**Comment by dcoeurjo** [comment]
I'm on the MacOS Sierra beta. It could be related to my issue but ```ntfy```  works fine with pushbullet for instance

**Comment by dschep** [comment]
Hrmm. Yeah I _really_ don't know how I'll test that :wink:

**Comment by dcoeurjo** [comment]
I'll try with another Mac (El Capitan MacOs) to check if I can reproduce my bug.. BTW, thanks @dschep btw, nice tool

**Comment by dcoeurjo** [comment]
On Sierra, everything seems to work after a ```pip install pyobjc``` 🎉

**Comment by dschep** [comment]
Cool. Does that install cleanly & work on older versions of MacOS too? If so I'll add a conditional dependency like Windows has: https://github.com/dschep/ntfy/blob/master/setup.py#L9

**Comment by dcoeurjo** [comment]
I'll try and keep you in touch.

**Comment by gibsjose** [comment]
I can confirm I get the same issues on OS X El Capitan.

Installing `pyobjc` as we speak. It's taking forever, though.

Looking at the [installation instructions](https://pythonhosted.org/pyobjc/install.html) for `pyobjc`, it looks like it tries to constantly install `pyobjc-core`, so you have to install with:

```bash
$ pip install -U pyobjc-core
$ pip install -U pyobjc
```

**Comment by gibsjose** [comment]
Works great after installing `pyobjc`!

And indeed, it takes on the order of 2-3 minutes to install `pyobjc` using the two-step process above, whereas it takes nearly an hour to install it if you just naïvely run `pip install pyobjc`.

**Comment by dcoeurjo** [comment]
I confirm (pyobjc required also on El Capitan). Thanks for the ```-U``` tip 😃

**Comment by dschep** [comment]
Thanks guys! I'll update the `setup.py`.

**Comment by austinbutler** [comment]
Did this ever make it into the released version? Just got the same error and had to install these dependencies manually.

```
ERROR: Failed to send notification using default
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/ntfy/backends/default.py", line 20, in notify
    module.notify(title=title, message=message, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/ntfy/backends/darwin.py", line 6, in notify
    import Foundation
ModuleNotFoundError: No module named 'Foundation'

During handling of the above exception, another exception occurred:


Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/ntfy/__init__.py", line 65, in notify
    **backend_config)
  File "/usr/local/lib/python3.6/site-packages/ntfy/backends/default.py", line 22, in notify
    raise DefaultNotifierError(e, module)
ntfy.backends.default.DefaultNotifierError: (ModuleNotFoundError("No module named 'Foundation'",), <
module 'ntfy.backends.darwin' from '/usr/local/lib/python3.6/site-packages/ntfy/backends/darwin.py'>
)
```

Works after `pip3 install pyobjc-core pyobjc`.

**Comment by fuzzy76** [comment]
It did, but was removed again in https://github.com/dschep/ntfy/commit/92af467796f4480256822a7e42e912c567fa8d3d due to #122 so the last release shipped without.

... And was later readded in https://github.com/dschep/ntfy/commit/e753c9601340582ef302a62115034144f70ec67c , but that haven't been released yet.

**Comment by dschep** [comment]
Yeah I added it back to the deps since PyObjc was updated (had someone else test install it for me). I should probably cut a new release (need to fix the build first)
