### ISSUE TITLE
Demo setup

### ISSUE THREAD

**Issue by black-perl** [dschep/ntfy#88]
Hi,

Nice work. Would you bother to explain the demo video setup you have ? 
I guess you are running commands on your android phone ?

Thanks.

**Comment by dschep** [comment]
I ran Ubuntu in a VM (my desktop isn't very pretty :wink:), that was recorded with xvidcap & the Android part of the demo was recorded on my Nexus5x with `adb`. I then edited them together with.. I honestly don't remember what. It's available in the Ubuntu repos, PiTiVi or OpenShot.

**Comment by black-perl** [comment]
Okay,  thanks for explaining. I am particularly interested in the notifications part on your Android  phone. Running commands through adb invoke your terminal app on phone or there's something else.

**Comment by dschep** [comment]
Nope, the notifications are delivered via Pushover & Pushbullet and sent by ntfy as they would be in real world use, `adb` is just for video: https://developer.android.com/studio/command-line/shell.html#screenrecord
