### ISSUE TITLE
Enhancement: Web push

### ISSUE THREAD

**Issue by phubbard** [dschep/ntfy#98]
I am looking for a tool to let me send web push notifications to browsers. Even IE is adding support, and it'd be a killer way to reach users. Is that in scope?

**Comment by dschep** [comment]
Probably out of scope. That'd be actually implementing a "backend" (where the "backend" modules in `ntfy` are just the code to connect to one).

In fact, the [pushover web client](https://client.pushover.net/) uses browser notifications so technically `ntfy` already supports browser push notifications :wink:
